
# █░█ █▀ █▀▀ █▀█   █▀█ █▀█ █▀▀ █▀▀ █▀
# █▄█ ▄█ ██▄ █▀▄   █▀▀ █▀▄ ██▄ █▀░ ▄█

# Set your personal hyprland configuration here
# See https://wiki.hyprland.org/Configuring for more information

# Start My Applications at Startup
exec-once = sleep 4 && rog-control-center

# // █ █▄░█ █▀█ █░█ ▀█▀
# // █ █░▀█ █▀▀ █▄█ ░█░


#  Uncomment to enable // change to a preferred value
# 🔗 See https://wiki.hyprland.org/Configuring/Variables/#input
input {
    kb_layout = us
    follow_mouse = 1
    # sensitivity = 0
    # force_no_accel = 0
    accel_profile = flat 
    # numlock_by_default = true
    natural_scroll = false

    # 🔗 See https://wiki.hyprland.org/Configuring/Variables/#touchpad
    touchpad {
        natural_scroll = true
        scroll_factor = 0.5
    }

}

# 🔗 See https://wiki .hyprland.org/Configuring/Variables/#gestures
gestures {
     workspace_swipe = true
     workspace_swipe_fingers = 3
}
